### ISSUE TITLE
cant open my q zone after using this extension

### ISSUE THREAD

**Issue by Florence-27** [ShunCai/QZoneExport#47]
hi there, 

i got an issue in open my qzone, i try open it a lot of time, but it keeps showing a page telling me the page is lost (网页走丢了). pls help and giving us an solution in fix it.

many thanks

**Comment by ShunCai** [comment]
Do you see the buttons managed by your organization in the browser menu or configure the browser’s extended whitelist in the system group policy? 

I seem to have encountered this problem before, just remove the relevant whitelist configuration in the Windows registry. 

You can open chrome://policy/ tab to see if the extension whitelist is configured, or search for Managed by your organization in Google

**Comment by Florence-27** [comment]
Thank you for reply me that quick mate! i would try this tmr, is that also got a whitelist in the 360 browser(the green colour one)? cuz I also try open it through the 360 browser, it also shows that the page is lost.

**Comment by ShunCai** [comment]
Maybe, but I’m not sure if it will affect the 360 browser, because I didn’t install the 360 browser at the time. You can try to delete the values below the registry \HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome. It is recommended to delete it first Backup, and then restart the browser.

**Comment by ShunCai** [comment]
I tried to add Chrome’s extension whitelist, but the error is different from yours. Can you provide the URL and screenshot of the error page?

![image](https://user-images.githubusercontent.com/39191272/97794685-22a64380-1c38-11eb-9263-7f6170653666.png)

**Comment by Florence-27** [comment]
Hi ShunCai,

lovely! I will provide it tmr night, cuz that’s my friend’s account! u r a super efficiency developer!! Really appreciate!

**Comment by ShunCai** [comment]
Okay, on the tmr night, you can try to disable QZoneExport, and then try to open [QZone](https://qzone.qq.com/) again. If it still fails to open, I think it has nothing to do with QZoneExport installed, you can try to refresh the local DNS cache.

**Comment by Florence-27** [comment]
cool, I will try that~, but maybe I am not quite know about the local dns
cache, but I will try google it first😭

**Comment by Florence-27** [comment]
hey mate,

The Qzone now is able to access now after we uninstalled the qq影像空間, very appropriate for ur help during these day!! 

Apart from it, we are unable to install the photo from the qzone albums, it turns out the download is failed. How to solved this problem mate?

Looking forward to hearing from you mate!

Florence Yip

**Comment by ShunCai** [comment]
Pls confirm the common configuration items on the QZoneExport option page

The path is Option -> [公共] Common Tab->[文件下载]File Download->[文件下载工具]File Download Tool.

The default download tool of QZoneExport is internal download. 

It is recommended to change the file download tool to Browser[浏览器（推荐）], ThunderX[迅雷X（自动唤起）] or Aria2, because the default download tool is more limited.

for example, it is only suitable for users with less QZone data, and image downloads that are more suitable for https address.

But, for the browser download tool, there may be some videos that cannot be downloaded. because cannot bypass QZone's anti-theft chain, and I am still looking for a solution.

For the videos, you can switch to Thunder download or Aria2 download on the QZoneExport download management page.

Of course, the best solution is change the download tool to Thunder or Aria2  , because ThunderX and Aria2 can download the videos.
However, ThunderX or Aria2 must be installed first.
